apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
type: Opaque
stringData:
  # Example value. Use your real credentials in your environment.
  url: amqp://username:password@rabbitmq.default.svc.cluster.local:5672/
